name: Weather report
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get install curl
      - name: Weather report
        run: curl -o weather.json "https://api.openweathermap.org/data/2.5/weather?lat=41.6414438&lon=-80.15144839999999&appid=$API"
        env:
          API: ${{ secrets.OpenWeather }}
      - name: Publish weather report
        uses: actions/upload-artifact@v3
        with:
          name: Weather Report
          path: /weather.json
